name: ship_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.3
  google_maps_flutter: ^2.18.0
  permission_handler: ^12.0.3
  flutter_map: ^7.0.2 # OSM-based map, free, no API key needed
  latlong2: ^0.9.1 # LatLng type used by flutter_map
  flutter_map_marker_cluster: ^1.4.0 # clustering for dense marker areas
  http: ^1.2.2 # for calling your backend/MarineTraffic proxy later
  flutter_riverpod: ^2.6.1 # state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#0A2472"
  color_dark: "#0A2472"

  # Legacy Android (<12) and iOS both use this
  image: assets/images/splash_logo_ios.png

  android_12:
    image: assets/images/splash_logo_android.png # 960x960, boat centered within 640px safe zone
    icon_background_color: "#0A2472"
    icon_background_color_dark: "#0A2472"

  web: false
